[package]
name = "cribtic"
version = "0.1.0"
edition = "2021"

[lib]
name = "cribtic"
path = "src/lib.rs"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.29", features = ["derive"] }
rand = "0.8.5"
rsa = { version = "0.9.7" }
